language: objective-c
osx_image: xcode7.3

script:
  - echo "Start iOS Builds"
  - cd "iOS-text-chat/TextChatSample/"
  - pod install
  - cd "../.."
  - xcodebuild clean test -workspace "iOS-text-chat/TextChatSample/TextChatSample.xcworkspace" -scheme "TextChatSampleTests" -sdk "iphonesimulator9.3" -destination "OS=9.0,name=iPhone 6 Plus" -configuration Debug ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
  - xcodebuild clean build -project "iOS-text-chat/Documentation/Documentation.xcodeproj" -scheme "AppleDoc" -sdk "iphonesimulator9.3" -destination "OS=9.0,name=iPhone 6 Plus" -configuration Debug | xcpretty -c
  - echo "End iOS Builds"
